package com.quartz.web.dao;

import com.quartz.web.pojo.QrtzJobDetails;
import com.quartz.web.pojo.QrtzJobDetailsExample;
import com.quartz.web.pojo.QrtzJobDetailsKey;
import java.util.List;

public interface QrtzJobDetailsDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    void insert(QrtzJobDetails record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int updateByPrimaryKeyWithoutBLOBs(QrtzJobDetails record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int updateByPrimaryKeyWithBLOBs(QrtzJobDetails record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int updateByPrimaryKeySelective(QrtzJobDetails record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    List<QrtzJobDetails> selectByExampleWithoutBLOBs(QrtzJobDetailsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    List<QrtzJobDetails> selectByExampleWithBLOBs(QrtzJobDetailsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    QrtzJobDetails selectByPrimaryKey(QrtzJobDetailsKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int deleteByExample(QrtzJobDetailsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int deleteByPrimaryKey(QrtzJobDetailsKey key);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int countByExample(QrtzJobDetailsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int updateByExampleSelective(QrtzJobDetails record, QrtzJobDetailsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int updateByExampleWithBLOBs(QrtzJobDetails record, QrtzJobDetailsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int updateByExampleWithoutBLOBs(QrtzJobDetails record, QrtzJobDetailsExample example);
}