package com.quartz.web.pojo;

public class QrtzJobDetails extends QrtzJobDetailsKey {
	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_job_details.JOB_GROUP
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String jobGroup;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_job_details.JOB_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String jobName;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_job_details.JOB_GROUP
     *
     * @return the value of qrtz_job_details.JOB_GROUP
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_job_details.JOB_GROUP
     *
     * @param jobGroup the value for qrtz_job_details.JOB_GROUP
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_job_details.JOB_NAME
     *
     * @return the value of qrtz_job_details.JOB_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_job_details.JOB_NAME
     *
     * @param jobName the value for qrtz_job_details.JOB_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_job_details.DESCRIPTION
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String description;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_job_details.JOB_CLASS_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String jobClassName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_job_details.IS_DURABLE
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String isDurable;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_job_details.IS_VOLATILE
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String isVolatile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_job_details.IS_STATEFUL
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String isStateful;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_job_details.REQUESTS_RECOVERY
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String requestsRecovery;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_job_details.JOB_DATA
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private byte[] jobData;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_job_details.DESCRIPTION
     *
     * @return the value of qrtz_job_details.DESCRIPTION
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_job_details.DESCRIPTION
     *
     * @param description the value for qrtz_job_details.DESCRIPTION
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_job_details.JOB_CLASS_NAME
     *
     * @return the value of qrtz_job_details.JOB_CLASS_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getJobClassName() {
        return jobClassName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_job_details.JOB_CLASS_NAME
     *
     * @param jobClassName the value for qrtz_job_details.JOB_CLASS_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setJobClassName(String jobClassName) {
        this.jobClassName = jobClassName == null ? null : jobClassName.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_job_details.IS_DURABLE
     *
     * @return the value of qrtz_job_details.IS_DURABLE
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getIsDurable() {
        return isDurable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_job_details.IS_DURABLE
     *
     * @param isDurable the value for qrtz_job_details.IS_DURABLE
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setIsDurable(String isDurable) {
        this.isDurable = isDurable == null ? null : isDurable.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_job_details.IS_VOLATILE
     *
     * @return the value of qrtz_job_details.IS_VOLATILE
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getIsVolatile() {
        return isVolatile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_job_details.IS_VOLATILE
     *
     * @param isVolatile the value for qrtz_job_details.IS_VOLATILE
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setIsVolatile(String isVolatile) {
        this.isVolatile = isVolatile == null ? null : isVolatile.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_job_details.IS_STATEFUL
     *
     * @return the value of qrtz_job_details.IS_STATEFUL
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getIsStateful() {
        return isStateful;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_job_details.IS_STATEFUL
     *
     * @param isStateful the value for qrtz_job_details.IS_STATEFUL
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setIsStateful(String isStateful) {
        this.isStateful = isStateful == null ? null : isStateful.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_job_details.REQUESTS_RECOVERY
     *
     * @return the value of qrtz_job_details.REQUESTS_RECOVERY
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getRequestsRecovery() {
        return requestsRecovery;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_job_details.REQUESTS_RECOVERY
     *
     * @param requestsRecovery the value for qrtz_job_details.REQUESTS_RECOVERY
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setRequestsRecovery(String requestsRecovery) {
        this.requestsRecovery = requestsRecovery == null ? null : requestsRecovery.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_job_details.JOB_DATA
     *
     * @return the value of qrtz_job_details.JOB_DATA
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public byte[] getJobData() {
        return jobData;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_job_details.JOB_DATA
     *
     * @param jobData the value for qrtz_job_details.JOB_DATA
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setJobData(byte[] jobData) {
        this.jobData = jobData;
    }
}