package com.quartz.web.pojo;

public class QrtzJobDetailsKey {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_job_details.JOB_GROUP
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String jobGroup;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_job_details.JOB_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String jobName;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_job_details.JOB_GROUP
     *
     * @return the value of qrtz_job_details.JOB_GROUP
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_job_details.JOB_GROUP
     *
     * @param jobGroup the value for qrtz_job_details.JOB_GROUP
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_job_details.JOB_NAME
     *
     * @return the value of qrtz_job_details.JOB_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_job_details.JOB_NAME
     *
     * @param jobName the value for qrtz_job_details.JOB_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }
}