package com.quartz.web.pojo;

public class QrtzUsers {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_users.ID
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_users.USER_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String userName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_users.USER_PASSWORD
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String userPassword;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_users.USER_GROUP
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String userGroup;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_users.USER_JOB_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String userJobName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qrtz_users.USER_TRIGGER_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private String userTriggerName;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_users.ID
     *
     * @return the value of qrtz_users.ID
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_users.ID
     *
     * @param id the value for qrtz_users.ID
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_users.USER_NAME
     *
     * @return the value of qrtz_users.USER_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_users.USER_NAME
     *
     * @param userName the value for qrtz_users.USER_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_users.USER_PASSWORD
     *
     * @return the value of qrtz_users.USER_PASSWORD
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_users.USER_PASSWORD
     *
     * @param userPassword the value for qrtz_users.USER_PASSWORD
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_users.USER_GROUP
     *
     * @return the value of qrtz_users.USER_GROUP
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getUserGroup() {
        return userGroup;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_users.USER_GROUP
     *
     * @param userGroup the value for qrtz_users.USER_GROUP
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setUserGroup(String userGroup) {
        this.userGroup = userGroup == null ? null : userGroup.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_users.USER_JOB_NAME
     *
     * @return the value of qrtz_users.USER_JOB_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getUserJobName() {
        return userJobName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_users.USER_JOB_NAME
     *
     * @param userJobName the value for qrtz_users.USER_JOB_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setUserJobName(String userJobName) {
        this.userJobName = userJobName == null ? null : userJobName.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qrtz_users.USER_TRIGGER_NAME
     *
     * @return the value of qrtz_users.USER_TRIGGER_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public String getUserTriggerName() {
        return userTriggerName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qrtz_users.USER_TRIGGER_NAME
     *
     * @param userTriggerName the value for qrtz_users.USER_TRIGGER_NAME
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void setUserTriggerName(String userTriggerName) {
        this.userTriggerName = userTriggerName == null ? null : userTriggerName.trim();
    }
}