package com.quartz.web.dao;

import com.quartz.web.pojo.QrtzUsers;
import com.quartz.web.pojo.QrtzUsersExample;
import java.util.List;

public interface QrtzUsersDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    void insert(QrtzUsers record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int updateByPrimaryKey(QrtzUsers record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int updateByPrimaryKeySelective(QrtzUsers record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    List<QrtzUsers> selectByExample(QrtzUsersExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    QrtzUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int deleteByExample(QrtzUsersExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int countByExample(QrtzUsersExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int updateByExampleSelective(QrtzUsers record, QrtzUsersExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    int updateByExample(QrtzUsers record, QrtzUsersExample example);
}