package com.quartz.web.dao;

import com.quartz.web.pojo.QrtzUsers;
import com.quartz.web.pojo.QrtzUsersExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class QrtzUsersDAOImpl extends SqlMapClientDaoSupport implements QrtzUsersDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public QrtzUsersDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void insert(QrtzUsers record) {
        getSqlMapClientTemplate().insert("qrtz_users.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int updateByPrimaryKey(QrtzUsers record) {
        int rows = getSqlMapClientTemplate().update("qrtz_users.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int updateByPrimaryKeySelective(QrtzUsers record) {
        int rows = getSqlMapClientTemplate().update("qrtz_users.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<QrtzUsers> selectByExample(QrtzUsersExample example) {
        List<QrtzUsers> list = (List<QrtzUsers>) getSqlMapClientTemplate().queryForList("qrtz_users.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public QrtzUsers selectByPrimaryKey(Integer id) {
        QrtzUsers key = new QrtzUsers();
        key.setId(id);
        QrtzUsers record = (QrtzUsers) getSqlMapClientTemplate().queryForObject("qrtz_users.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int deleteByExample(QrtzUsersExample example) {
        int rows = getSqlMapClientTemplate().delete("qrtz_users.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int deleteByPrimaryKey(Integer id) {
        QrtzUsers key = new QrtzUsers();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("qrtz_users.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int countByExample(QrtzUsersExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("qrtz_users.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int updateByExampleSelective(QrtzUsers record, QrtzUsersExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("qrtz_users.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int updateByExample(QrtzUsers record, QrtzUsersExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("qrtz_users.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table qrtz_users
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private static class UpdateByExampleParms extends QrtzUsersExample {
        private Object record;

        public UpdateByExampleParms(Object record, QrtzUsersExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}