package com.quartz.web.dao;

import com.quartz.web.pojo.QrtzJobDetails;
import com.quartz.web.pojo.QrtzJobDetailsExample;
import com.quartz.web.pojo.QrtzJobDetailsKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class QrtzJobDetailsDAOImpl extends SqlMapClientDaoSupport implements QrtzJobDetailsDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public QrtzJobDetailsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public void insert(QrtzJobDetails record) {
        getSqlMapClientTemplate().insert("qrtz_job_details.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int updateByPrimaryKeyWithoutBLOBs(QrtzJobDetails record) {
        int rows = getSqlMapClientTemplate().update("qrtz_job_details.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int updateByPrimaryKeyWithBLOBs(QrtzJobDetails record) {
        int rows = getSqlMapClientTemplate().update("qrtz_job_details.abatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int updateByPrimaryKeySelective(QrtzJobDetails record) {
        int rows = getSqlMapClientTemplate().update("qrtz_job_details.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<QrtzJobDetails> selectByExampleWithoutBLOBs(QrtzJobDetailsExample example) {
        List<QrtzJobDetails> list = (List<QrtzJobDetails>) getSqlMapClientTemplate().queryForList("qrtz_job_details.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<QrtzJobDetails> selectByExampleWithBLOBs(QrtzJobDetailsExample example) {
        List<QrtzJobDetails> list = (List<QrtzJobDetails>) getSqlMapClientTemplate().queryForList("qrtz_job_details.abatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public QrtzJobDetails selectByPrimaryKey(QrtzJobDetailsKey key) {
        QrtzJobDetails record = (QrtzJobDetails) getSqlMapClientTemplate().queryForObject("qrtz_job_details.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int deleteByExample(QrtzJobDetailsExample example) {
        int rows = getSqlMapClientTemplate().delete("qrtz_job_details.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int deleteByPrimaryKey(QrtzJobDetailsKey key) {
        int rows = getSqlMapClientTemplate().delete("qrtz_job_details.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int countByExample(QrtzJobDetailsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("qrtz_job_details.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int updateByExampleSelective(QrtzJobDetails record, QrtzJobDetailsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("qrtz_job_details.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int updateByExampleWithBLOBs(QrtzJobDetails record, QrtzJobDetailsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("qrtz_job_details.abatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    public int updateByExampleWithoutBLOBs(QrtzJobDetails record, QrtzJobDetailsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("qrtz_job_details.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table qrtz_job_details
     *
     * @abatorgenerated Thu Aug 02 17:44:42 CST 2012
     */
    private static class UpdateByExampleParms extends QrtzJobDetailsExample {
        private Object record;

        public UpdateByExampleParms(Object record, QrtzJobDetailsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}